export { EmbeddingService, makeEmbeddingService } from "./ai"
export { store } from "./vectorize"
export { ApiError, ParseError } from "shared"
export { VectorRecordSchema } from "./schema"
export type { VectorRecord } from "./schema"
